export const AUTHORISE_USER = "AUTHORISE_USER";
export const BASICFORM_SUBMIT = "BASICFORM_SUBMIT";
export const GET_EVENT_DETAILS = "GET_EVENT_DETAILS";
export const BASICFORM_STATE = "BASICFORM_STATE";